### ISSUE TITLE
Add results and doc

### ISSUE THREAD

**Issue by rswgnu** [xuchunyang/elisp-demos#6]
Why don’t you show the result value of each expression in the Elisp API Demos. Then people could immediately have an idea of what each does, also the first line of doc or a summary would be helpful.

You shouldn’t have to run everything to get an idea of what each function does.

**Comment by xuchunyang** [comment]
The result values are stored in elisp-demos.org, e.g.,

```
* mapcar

#+BEGIN_SRC elisp
(mapcar #'1+ '(1 2 3))
#+END_SRC

#+RESULTS:
: (2 3 4)
```

however, github's org mode render does not show the result block. You're suggested to try the C-h f integration as shown in the README, and the docstring is already there.

**Comment by rswgnu** [comment]
Ok, thanks.
