### ISSUE TITLE
Making the elisp demos file a custom variable

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [xuchunyang/elisp-demos#8]
Could the elisp demos org file be a custom variable? I'd be nice if I could conveniently make it a file of my choosing instead of editing the file that comes with the package.

**Comment by xuchunyang** [comment]
You can change the value of `elisp-demos--elisp-demos.org`, although it's a const and private variable.

**Comment by Luis-Henriquez-Perez** [comment]
> You can change the value of elisp-demos--elisp-demos.org, although it's a const and private variable.

Fair enough.

Also, is there a way to specify that I still want to use the demos from `elisp-demos--elisp-demos.org` but just want to add my own examples in a separate file?

**Comment by xuchunyang** [comment]
No, it's hard-coded. Adding such feature requires some work but I don't have time.

There are some **inconvenient** work-arounds such as
- concatenate your demo file and elisp-demos.org into one file
- advice the function elisp-demos--search to support multiple files

**Comment by Luis-Henriquez-Perez** [comment]
Ok, thank you for your suggestions. I'll close this then.
